// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfS8FdbuPokmQOjrXzAczq8SV3kSz0zQ',
    appId: '1:206521139828:web:ca530726c873169aa4c721',
    messagingSenderId: '206521139828',
    projectId: 'login-signup-authproject',
    authDomain: 'login-signup-authproject.firebaseapp.com',
    storageBucket: 'login-signup-authproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_9wgcJjmjy8yXn4AG7XhQHv0TqeMcLMQ',
    appId: '1:206521139828:android:6c1f3a8e42239716a4c721',
    messagingSenderId: '206521139828',
    projectId: 'login-signup-authproject',
    storageBucket: 'login-signup-authproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdX9Q_6phpaRzUst6KHlbcO2VMwehWx4U',
    appId: '1:206521139828:ios:20be7c751e32e548a4c721',
    messagingSenderId: '206521139828',
    projectId: 'login-signup-authproject',
    storageBucket: 'login-signup-authproject.appspot.com',
    iosBundleId: 'com.example.logsignflutter',
  );
}
